apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
  labels:
    app: express
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express-app
        image: marviigrey/express-app
        